### ISSUE TITLE
Move code from Vercel to Cloudflare pages

### ISSUE THREAD

**Issue by PhilipLeth** [AutomationApp/Promo-site#14]
Right now we pay 20 usd pr. user on Vercel pr. month.!

Cloudflare pages should be possible to use instead.?
From github master branch - deploy the Gatsby code to the cloudflare pages.

Cloudflare pages gatsby
https://developers.cloudflare.com/pages/framework-guides/deploy-a-gatsby-site/

Point the cloudflare DNS when done :) 
https://dash.cloudflare.com/ec10aafcd3d2e7c56aa73c53d3b5d27d/automation.app

**Comment by jespermb** [comment]
I was thinking the same
